server:
  port: 9099

spring:
  application:
    name: apigateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/